# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|

  config.vm.define :developmentbox do |developmentbox|

    # on which base box this box will be setup from
    developmentbox.vm.box = "testbox"

    developmentbox.vm.boot_mode = :gui

    # developmentbox.vm.forward_port 80, 8080
    # developmentbox.vm.share_folder "v-data", "/vagrant_data", "../data"
    #
    developmentbox.vm.network :hostonly, "192.168.23.42", :auto_config => true, :adapter => 2
    developmentbox.ssh.forward_agent = true
    
    developmentbox.vm.provision :puppet do |puppet|
      puppet.manifests_path = "./"
      puppet.manifest_file  = "manifest.pp"
      puppet.module_path = "../../modules"
      puppet.options = "--verbose --debug"
    end
  end
end
