# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|


  config.vm.define :cibox do |cibox|

    # identifier that we want the box to be named
    cibox.package.name = "cibox"

    # base_box of our BASE BOX
    #cibox.vm.box = "squeeze64"
    cibox.vm.box = "basebox"

    # you can set your own url here, but make sure that you do not maintain this box to stay
    # clear of your project scope. it ends here.
    cibox.vm.box_url = "http://puppetlabs.s3.amazonaws.com/pub/squeeze64.box"

    # left it here for dev purpose, don't need it really
    cibox.vm.boot_mode = :gui

    # cibox.vm.forward_port 80, 8080
    # cibox.vm.share_folder "v-data", "/vagrant_data", "../data"

    # as you don't start this vm at the same time as the successor it is ok to have
    # the same ip for every Vagrantfile
    cibox.vm.network :hostonly, "192.168.23.44", :auto_config => true, :adapter => 2

    # we want to run git in the vm
    cibox.ssh.forward_agent = true

    cibox.vm.customize ["modifyvm", :id, "--memory", 512]

    # the manifest.pp is in the same directory as the Vagrantfile
    cibox.vm.provision :puppet do |puppet|
      puppet.manifests_path = "./"
      puppet.manifest_file  = "manifest.pp"
      puppet.module_path = "../../modules"
      puppet.options = "--verbose --debug"
    end
  end
end
